name: swin
bundle_seq_length: 1
latent_dim: 128
num_layers: 2

swin:
  patch_size: [ 4, 2, 4, 8, 4 ]
  window_size: [ 4, 2, 2, 8, 4 ]
  num_heads: [2, 8]
  depth: [2, 2]
  c_multiplier: 2
  gradient_checkpoint: false
  patching_hidden_ratio: 12.0
  timestep_conditioning: true