name: swin_flat
bundle_seq_length: 1
latent_dim: 384
num_layers: 1

swin:
  patch_size: [ 4, 2, 4, 8, 4 ]
  window_size: [ 4, 2, 2, 8, 4 ]
  num_heads: [12]
  depth: [16]
  gradient_checkpoint: false
  merging_hidden_ratio: 4.0
  unmerging_hidden_ratio: 8.0
  timestep_conditioning: true
  itg_conditioning: true
  c_multiplier: 2
  norm_output: false
  abs_pe: true
  act_fn: GELU
  patch_skip: true
  modulation: dit
  drop_path: 0.1
  swin_bottleneck: true
  latent_cross_attn: true
  flux_head: false