name: swin
bundle_seq_length: 1
latent_dim: 32
num_layers: 3

swin:
  patch_size: [ 4, 2, 4, 8, 4 ]
  window_size: [ 4, 2, 2, 8, 4 ]
  num_heads: [2, 4, 8]
  depth: [2, 4, 8]
  gradient_checkpoint: false
  patching_hidden_ratio: 12.0
  timestep_conditioning: true