name: swin
bundle_seq_length: 1
latent_dim: 256
num_layers: 1

swin:
  patch_size: [ 4, 2, 4, 8, 4 ]
  window_size: [ 4, 2, 2, 8, 4 ]
  num_heads: [8]
  depth: [2]
  gradient_checkpoint: false
  merging_hidden_ratio: 4.0
  unmerging_hidden_ratio: 8.0
  timestep_conditioning: true
  itg_conditioning: true
  c_multiplier: 2
  unmerging_layer_norm: false
  pre_ln: false
  norm_output: false
  abs_pe: false
  act_fn: GELU
  add_first_residual: true