name: swin
bundle_seq_length: 1
latent_dim: 128
num_layers: 2

swin:
  patch_size: [4, 2, 2, 6, 4]
  window_size: [4, 2, 4, 7, 3]
  num_heads: [4, 8]
  depth: [4, 8]
  gradient_checkpoint: false
  patching_hidden_ratio: 16.0
  timestep_conditioning: true