name: cyclone
path: /local00/bioinf/gyrokinetics/preprocessed
normalization: null
normalization_scope: dataset
minmax_beta1: 8
minmax_beta2: 4
offset: 80
subsample: 1
spatial_ifft: true
separate_zf: true
real_potens: true
split_into_bands: null
log_transform: false
num_workers: 4
active_keys: ["re", "im"]
input_fields: ["df"]
training_trajectories: "iteration_{0-7,9-12,14-99,101-114,116-130,132-147,149-199,201-234,236-261,263-299}.h5"
validation_trajectories: ["iteration_13.h5", "iteration_100.h5", "iteration_200.h5"]
partial_holdouts:
training_cond_filters:
  last_fluxes: [1., .inf]
  first_fluxes: [1., .inf]
eval_cond_filters:
  last_fluxes: [1., .inf]
  first_fluxes: [1., .inf]

augment:
  noise: false
  noise_std: 1e-4
