name: cyclone
path: /system/user/publicdata/gyrokinetics/preprocessed
normalization: zscore
normalization_scope: sample
spatial_ifft: true
in_memory: true
active_keys: ["re", "im"]
training_trajectories: ["cyclone6_2.h5", "cyclone7_2.h5", "cyclone8_2.h5"]
validation_trajectories: ["cyclone5_2.h5"]
partial_holdouts:
- trajectory: "cyclone6_2.h5"
  last_n: 10
- trajectory: "cyclone7_2.h5"
  last_n: 20
training_cond_filters:
eval_cond_filters:

augment:
  noise: false
  noise_std: 1e-4