name: cyclone
path: /local00/bioinf/gyrokinetics/preprocessed
normalization: zscore
normalization_scope: dataset
minmax_beta1: 8
minmax_beta2: 4
offset: 80
subsample: 1
val_subsample: 10
spatial_ifft: true
separate_zf: true
norm_decouple_mu: true
real_potens: true
split_into_bands: null
log_transform: false
num_workers: 4
active_keys: ["re", "im"]
input_fields: ["df"]
training_trajectories: "iteration_{0-5,7-12,14-31,33-82,84-99}.h5"
validation_trajectories: ["iteration_13.h5", "iteration_100.h5", "iteration_200.h5"]
# validation_trajectories: "ood_iteration_{0-4}.h5"
partial_holdouts:
training_cond_filters:
  last_fluxes: [1., .inf]
  first_fluxes: [1., .inf]
eval_cond_filters:
  last_fluxes: [1., .inf]
  first_fluxes: [1., .inf]

augment:
  noise: false
  noise_std: 1e-4

timestep_std_filter: null  # std-based timestep filtering threshold (null to disable)
timestep_std_offset: 80