name: cyclone
path: /restricteddata/ukaea/gyrokinetics/preprocessed
normalization: zscore
normalization_scope: dataset
minmax_beta1: 8
minmax_beta2: 4
offset: 0
subsample: 1
spatial_ifft: true
separate_zf: false
split_into_bands: null
log_transform: false
active_keys: ["re", "im"]
input_fields: ["df", "phi"]
training_trajectories: ["cyclone4_2_2.h5"]
validation_trajectories: ["cyclone4_2_2.h5"]
partial_holdouts:
training_cond_filters:
eval_cond_filters:

augment:
  noise: false
  noise_std: 1e-4