name: cyclone
path: /local01/bioinf/gyrokinetics/preprocessed
normalization: zscore
normalization_scope: trajectory
subsample: 1
no_zf: false
separate_zf: false
spatial_ifft: true
log_transform: false
active_keys: ["re", "im"]
training_trajectories: ["cyclone5_2.h5"]
validation_trajectories: ["cyclone4_2_2.h5"]
partial_holdouts:
training_cond_filters:
eval_cond_filters:

augment:
  noise: false
  noise_std: 1e-4