name: cyclone
path: /restricteddata/ukaea/gyrokinetics/preprocessed
normalization: zscore
normalization_scope: sample
spatial_ifft: false
in_memory: false
active_keys: ["re", "im"]
training_trajectories: ["cyclone4_2_2.h5"]
validation_trajectories: ["cyclone4_2_2.h5"]
partial_holdouts:

augment:
  noise: false
  noise_std: 1e-4