batch_size: 3
n_epochs: 1
num_workers: 1
prefetch_factor: 1
pin_memory: false
learning_rate: 1e-3
final_learning_rate: 1e-6
weight_decay: 1e-5
exclude_from_weight_decay: ["cond"]
predict_delta: false
scheduler: "cosine"
clip_grad: true
clip_to: 1.0
gradnorm_balancer: "none"  # "none", "full", "pseudo"
pushforward:
  epochs: [-1, 100, 120, 140, 160, 180]
  unrolls: [1, 2, 3, 5, 5, 10]
  probs: [10, 10, 10, 5, 5, 5]
