batch_size: 6
n_epochs: 100
num_workers: 4
pin_memory: true
learning_rate: 1e-3
final_learning_rate: 1e-6
weight_decay: 1e-5
predict_delta: false
scheduler: "cosine"
clip_grad: false
pushforward:
  epochs: [-1, 40, 70]
  unrolls: [1, 2, 3]
  probs: [10, 5, 5]

pretraining: true
pretraining_kwargs:
  freeze_after: true
  clip_grad: false
  scheduler: null
  lr: 5e-4
  n_epochs: 20
  target_modules: [patch_embed, unpatch]
  weight_decay: 1e-5

