batch_size: 4
n_epochs: 500
num_workers: 8
learning_rate: 5e-4
final_learning_rate: 1e-6
weight_decay: 1e-8
predict_delta: False
pushforward:
  epochs: [-1, 150, 300]
  unrolls: [1, 2, 3]
  probs: [10, 2, 1]
