batch_size: 2
n_epochs: 200
num_workers: 8
sampler: "trajectory"
learning_rate: 5e-4
final_learning_rate: 1e-6
weight_decay: 1e-8
predict_delta: False
pushforward:
  epochs: [-1, 50, 100, 150]
  unrolls: [2, 2, 4, 8]
  probs: [10, 5, 3, 2]
