name: ae
model_type: ae
bundle_seq_length: 1
latent_dim: 1024
act_fn: GELU
decouple_mu: true
conditioning: ["itg", "dg", "s_hat", "q"]
extra_zf_loss: false
init_weights: "kaiming_uniform"  # "xavier_uniform", "truncnormal", "kaiming_uniform"
patching_init_weights: "kaiming_uniform"
cond_init_weights: "kaiming_uniform"  # "kaiming_uniform", "normal_smallvar", "xavier_uniform"

loss_scheduler: null
loss_weights:
  df: 1.0
extra_loss_weights: {}

patch:
  patch_size: [ 4, 0, 4, 5, 4 ]
  window_size: [ 4, 0, 4, 9, 4 ]
  merging_depth: 1
  unmerging_depth: 1
  merging_hidden_ratio: 1.0
  unmerging_hidden_ratio: 1.0
  c_multiplier: 1.0

vit:
  num_heads: [8, 16]
  depth: [4, 4]
  gradient_checkpoint: false
  use_abs_pe: false
  use_rpb: true
  use_rope: false
  gated_attention: true
  modulation: dit  # "dit", "film"
  drop_path: 0.1
  qk_norm: true

bottleneck:
  dim: 256
  norm_learnable: false
  normalized_latent: true
  num_heads: 4
  depth: 2