name: ae
model_type: ae
bundle_seq_length: 1
latent_dim: 2048
act_fn: GELU
norm_fn: RMSNorm
decouple_mu: true
encoder_conditioning: ["itg", "dg", "s_hat", "q"]
decoder_conditioning: ["itg", "dg", "s_hat", "q"]
extra_zf_loss: false
init_weights: "kaiming_uniform"  # "xavier_uniform", "truncnormal", "kaiming_uniform"
patching_init_weights: "kaiming_uniform"
cond_init_weights: "kaiming_uniform"  # "kaiming_uniform", "normal_smallvar", "xavier_uniform"
freeze_ae: false  # true to train only the flux head

loss_scheduler: {}
loss_weights:
  df: 1.0
  # flux: 1.0
extra_loss_weights: {}

# flux_head:
#   enable: true
#   type: "cross_attn"  # "mlp", "cross_attn"
#   flux_dim: 1  # heat flux (eflux)
#   dim: 256
#   depth: 1
#   num_heads: 8
#   mlp_ratio: 2.0

patch:
  patch_size: [ 4, 0, 4, 5, 4 ]
  window_size: [ 4, 0, 4, 9, 4 ]
  merging_depth: 2
  unmerging_depth: 2
  merging_hidden_ratio: 1.0
  unmerging_hidden_ratio: 1.0
  c_multiplier: 1.0

vit:
  num_heads: [32]
  depth: [8]
  gradient_checkpoint: false
  use_abs_pe: false
  use_rpb: true
  use_rope: false
  gated_attention: true
  modulation: dit  # "dit", "film"
  drop_path: 0.1
  qk_norm: true

bottleneck:
  dim: 64
  norm_learnable: false
  normalized_latent: false
  num_heads: 4
  depth: 2