name: simsiam
model_type: simsiam
bundle_seq_length: 1
latent_dim: 1024
act_fn: GELU
decouple_mu: true
conditioning: ["itg", "dg", "s_hat", "q"]  # "timestep"
# conditioning: []  # for no conditioning
extra_zf_loss: false
init_weights: "kaiming_uniform"  # "xavier_uniform", "truncnormal", "kaiming_uniform"
patching_init_weights: "kaiming_uniform"
cond_init_weights: "kaiming_uniform"  # "kaiming_uniform", "normal_smallvar", "xavier_uniform"

loss_scheduler:
  df: null
  phi: null
  flux: null
  phi_int: null
  flux_int: null
    # start: 0.0
    # end: 1.0
    # start_fraction: 0.5
    # end_fraction: 0.7
  phi_cross: null
  flux_cross: null
  vq_commit: null
loss_weights:
  df: 1.0
  vq_commit: 1.0
extra_loss_weights:
  # flux_int: 1e-4
  # phi_int: 1e-4

patch:
  patch_size: [ 4, 0, 2, 5, 4 ]
  window_size: [ 4, 0, 4, 9, 4 ]
  merging_hidden_ratio: 1.0
  unmerging_hidden_ratio: 1.0
  c_multiplier: 1.0

vit:
  num_heads: [8, 16]
  depth: [4, 4]
  gradient_checkpoint: false
  use_abs_pe: false
  use_rpb: true
  use_rope: false
  gated_attention: false
  modulation: dit # "dit", "film"
  drop_path: 0.0

bottleneck:
  dim: 128
  norm_learnable: false
  num_heads: 2
  depth: 2
