name: vae
model_type: vae
bundle_seq_length: 1
latent_dim: 1024
act_fn: GELU
norm_fn: RMSNorm
beta_vae: 1.0
decouple_mu: true
encoder_conditioning: []
decoder_conditioning: ["itg", "dg", "s_hat", "q"]
extra_zf_loss: false
init_weights: "kaiming_uniform"  # "xavier_uniform", "truncnormal", "kaiming_uniform"
patching_init_weights: "kaiming_uniform"
cond_init_weights: "normal_smallvar"  # "kaiming_uniform", "normal_smallvar", "xavier_uniform"

loss_scheduler:
  df: null
  beta_vae:
    type: "linear"
    start: 0.0
    end: 0.06
    start_fraction: 0.05
    end_fraction: 0.9
loss_weights:
  df: 1.0
  beta_vae: 1.0
extra_loss_weights: {}

patch:
  patch_size: [ 4, 0, 4, 5, 4 ]
  window_size: [ 4, 0, 4, 9, 4 ]
  merging_depth: 2
  unmerging_depth: 2
  merging_hidden_ratio: 1.0
  unmerging_hidden_ratio: 1.0
  c_multiplier: 1.0

vit:
  num_heads: [16]
  depth: [8]
  gradient_checkpoint: false
  use_abs_pe: false
  use_rpb: true
  use_rope: false
  gated_attention: true
  modulation: dit  # "dit", "film"
  drop_path: 0.1
  qk_norm: true

bottleneck:
  dim: 256
  norm_learnable: false
  normalized_latent: false
  num_heads: 4
  depth: 2