name: local_fno
bundle_seq_length: 1
latent_dim: 512
num_layers: 8
decouple_mu: true
conditioning: ["timestep", "itg", "dg", "s_hat", "q"]
extra_zf_loss: false
loss_scheduler:
  df: null
  phi:
    type: "linear"
    start: 0
    end: 1
    start_fraction: 0.5
    end_fraction: 0.7
  flux: 
    type: "linear"
    start: 0
    end: 1
    start_fraction: 0.7
    end_fraction: 0.9
  phi_int: null
  flux_int: null
  phi_cross: null
  flux_cross: null
loss_weights:
  df: 1.0
  phi: 0.1
  flux: 1e-5
extra_loss_weights:
  phi_int: 0.0
  flux_int: 0.0
  phi_cross: 0.0
  flux_cross: 0.0

swin:
  patch_size: [ 4, 2, 4, 5, 4 ]
