defaults:
  - _self_
  - dataset: mhd
  - model: fno
  - logging: no_logging
  - training: default
  - validation: default
  # - override hydra/launcher: litai

experiment_id: test
seed: 0
output_path: null
use_ddp: false
use_amp: true
mode: "train"
eval: true
device: "cuda"
ckpt_path: null
