defaults:
  - _self_
  - dataset: random
  - model: swin5d
  - logging: wandb
  - training: default
  - validation: default
  - override hydra/launcher: litai

experiment_id: test
seed: 0
output_path: null
use_ddp: false
use_amp: true
train: true
eval: true
device: "cuda"
ckpt_path: null
