defaults:
  - _self_
  - dataset: cyclone
  - model: multi
  - logging: wandb
  - training: default
  - validation: default
  # - override hydra/launcher: litai

experiment_id: test
seed: 0
output_path: null
ddp:
  enable: false
  n_nodes: 1
amp: 
  enable: true  # set to false when using rope or integrals in training (complex / fft)
  bfloat: false  # set to false for fno
mode: "train"
eval: true
device: "cuda"
load_ckpt: false