name: latent_dit
model_type: latent_dit
latent_dim: 512
minibatch_ot: true
vit:
  num_heads: 8
  depth: 4
  mlp_ratio: 4.0
  drop_path: 0.1
diffusion:
  noise_distribution: gaussian
  continuous_time: true
